name: Test and deploy Alokai

on:
  push:
    branches: [ 18.0 ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Create Test Database
        run: |
          echo "Creating test database..."
          /home/egap/.new-db

      - name: Run Tests
        run: |
          echo "Running tests..."
          /home/egap/.test

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          echo "-------- Deploying https://vsf-odoo18.labs.erpgap.com/ "
          /home/egap/.deploy
       