name: Build VSF

on:
  push:
    branches: [ 18.0 ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - run: |
        echo "-------- Deploying https://vsf-odoo18.labs.erpgap.com/ "
        /home/egap/.deploy
